language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get install -y libreoffice

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install html5lib==0.9999999
  - pip install -U setuptools
  - pip install coveralls
  - pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script:  export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache ; mkdir $LINO_CACHE_ROOT; inv initdb test

after_success: coveralls


