language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  
before_install:
  - # sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get install -y libxml2-dev libxslt-dev libffi-dev libcairo2-dev libpango1.0-dev python-dev  # fix "sorry, but this version only supports 100 named groups"
  - sudo apt-get install -y libreoffice python3-uno
  - libreoffice '--accept=socket,host=127.0.0.1,port=8100;urp;' &

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools
  - pip install coveralls
  - pip install Django==$DJANGO
  - pip install -r requirements.txt
  - pip install .
# command to run tests, e.g. python setup.py test
script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - inv cov --no-html

after_success:
  - coveralls


