language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
before_install:
  - # sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get install -y libreoffice python3-uno
  - libreoffice '--accept=socket,host=127.0.0.1,port=8100;urp;' &

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools
  - pip install coveralls
  - pip install Django==$DJANGO
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests, e.g. python setup.py test
script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - if [ $TRAVIS_PYTHON_VERSION == 2* ]; then inv cov; else inv initdb; fi;

after_script:
  - if [ $TRAVIS_PYTHON_VERSION == 2* ]; then coveralls; fi;


